# Generated by Django 5.0.6 on 2024-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://ivke-photo-album-demo.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fopera.ff4933f4.jpg&w=640&q=75",
                max_length=500,
            ),
        ),
    ]
