# Generated by Django 5.0.6 on 2024-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodapp", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(max_length=500),
        ),
    ]
